### ISSUE TITLE
starting / layout checklist

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_docs#1]
- [x] after reorg merge, doc 'aeon_mecha'
- [x] provide creating and building pages instructions (in new branches)
- [x] try adding submodules directly to `src/` ? (no longer necessary)
- [x] link to source code from built html
- [ ] could have two different online docs sites/repos: public, private

**Comment by jkbhagatio** [comment]
Closing as mostly done - will move private / public discussion to a discussion
